//================= REQUEST CODE ===================//
#define REGISTER_REQUEST 0
#define LOGIN_REQUEST 1

#define CREATE_GROUP_REQUEST 11
#define JOIN_GROUP_REQUEST 12
#define ACCESS_GROUP_REQUEST 13
#define LOGOUT_REQUEST 14
#define SHOW_GROUP_REQUEST 15
#define VIEW_GROUP_NO_JOIN 16
#define VIEW_GROUP_JOINED 17

#define UPLOAD_REQUEST 131
#define DOWNLOAD_REQUEST 132
#define DELETE_REQUEST 133
#define VIEW_FILES_REQUEST 134
#define BACK_REQUEST 135
#define KICK_MEMBER_REQUEST 136
#define APPROVE_REQUEST 137
#define NO_REQUEST_WERE_ACCEPTED 138
#define INVITE_MEMBER_REQUEST 139
#define VIEW_ALL_GROUP_REQUEST 140
#define QUIT_GROUP_REQUEST 141
#define VIEW_USERS_OF_GROUP_REQUEST 142
#define RENAME_REQUEST 143
#define ACCEPT_INVITE_REQUEST 144
#define VIEW_USER_NOT_IN_GROUP 145
#define VIEW_USER_IN_GROUP 146
#define VIEW_REQUEST_IN_GROUP 147
#define CREATE_FOLDER_REQUEST 148
#define VIEW_FOLDER_REQUEST 149
#define RENAME_FOLDER_REQUEST 150
#define DELETE_FOLDER_REQUEST 151
#define COPY_FOLDER_REQUEST 152
#define MOVE_FOLDER_REQUEST 153
#define RENAME_FILE_REQUEST 190
#define COPY_FILE_REQUEST 191
#define MOVE_FILE_REQUEST 192
#define DELETE_FILE_REQUEST 193


//==================================================//

//====================== ALERT =====================//
#define REGISTER_SUCCESS 800
#define LOGIN_SUCCESS 801
#define ACCOUNT_BLOCKED 802
#define CREATE_GROUP_SUCCESS 803
#define JOIN_GROUP_SUCCESS 804
#define ACCESS_GROUP_SUCCESS 805
#define LOGOUT_SUCCESS 806
#define UPLOAD_SUCCESS 807
#define MEMBER_WAS_KICKED 808
#define REQUESTED_TO_JOIN 809
#define APPROVE_SUCCESS 810
#define INVITE_SUCCESS 811
#define ACCEPT_SUCCESS 812
#define QUIT_GROUP_SUCCESS 813
#define KICK_MEMBER_SUCCESS 814
#define CREATE_FOLDER_SUCCESS 815
#define VIEW_FOLDER_SUCCESS 816
#define RENAME_FOLDER_SUCCESS 817
#define DELETE_FOLDER_SUCCESS 818
#define COPY_FOLDER_SUCCESS 819
#define MOVE_FOLDER_SUCCESS 820
#define DOWN_LOAD_SUCCESS 821
#define READY_TO_UPLOAD 822
#define READY_TO_DOWNLOAD 823
#define RENAME_FILE_SUCCESS 850
#define COPY_FILE_SUCCESS 851
#define MOVE_FILE_SUCCESS 852
#define DELETE_FILE_SUCCESS 853


//==================================================//

//===================== INVALID ====================//
#define INCORRECT_PASSWORD 900
#define EXISTENCE_USERNAME 901
#define EXISTENCE_GROUP_NAME 902
#define EXISTENCE_FILE_NAME 903
#define NON_EXISTENCE_USERNAME 904
#define NOT_OWNER_OF_GROUP 905
#define NO_FILE_TO_DELETE 906
#define NO_FILE_TO_DOWNLOAD 907
#define NO_GROUP_TO_JOIN 908
#define NO_MEMBER_TO_KICK 909
#define NO_GROUP_TO_ACCESS 910
#define ALREADY_REQUESTED_TO_JOIN 911
#define HAS_BEEN_INVITED 912
#define NO_REQUEST_TO_APPROVE 913
#define NO_INVITE 914
#define NO_MEMBER_TO_INVITE 915
#define NO_ACCEPT_INVITE 916
#define IS_OWNER_OF_GROUP 917
#define NO_FILE_TO_RENAME 918
#define FOLDER_EXISTS 919
#define JOINED_ALL_GROUP 920
#define PATH_NOT_EXIST 921
#define VIEW_FOLDER_FAIL 922
#define UPLOAD_FAILED 923
#define RENAME_FOLDER_FAIL 924
#define NOT_BELONG_THAT_GROUP 925
#define DELETE_FOLDER_FAIL 926
#define COPY_FOLDER_FAIL 927
#define MOVE_FOLDER_FAIL 928
#define RENAME_FILE_FAIL 929
#define COPY_FILE_FAIL 930
#define MOVE_FILE_FAIL 931
#define DELETE_FILE_FAIL 932
#define INVALID_FORMAT 999
//==================================================//
